from typing import Any, Dict, List, Optional

from app.models.prompt import (
    EpisodeProductionPrompts,
    ProductionPrompt,
    PromptAssetReference,
    SceneProductionPrompts,
)


class ProductionPromptGenerator:
    """
    Converts production execution data into prompts that can be consumed
    by image and video generation systems.

    This class does NOT generate images or videos.
    It only creates structured production instructions.
    """

    def generate(
        self,
        episode_id: str,
        title: str,
        production_execution: Dict[str, Any],
        asset_planning: Optional[Dict[str, Any]] = None,
    ) -> EpisodeProductionPrompts:
        """
        Generate production prompts for an episode.

        Parameters
        ----------
        episode_id:
            Episode identifier, for example EP001.

        title:
            Episode title.

        production_execution:
            The details generated by the PRODUCTION_EXECUTION stage.

        asset_planning:
            Optional asset planning data. If available, it is used to
            supplement asset references.

        Returns
        -------
        EpisodeProductionPrompts
            Structured production prompts for every shot.
        """

        target_duration_seconds = int(
            production_execution.get("target_duration_seconds", 0)
        )

        execution_scenes = production_execution.get("scenes", [])

        scenes: List[SceneProductionPrompts] = []

        total_shots = 0

        for scene in execution_scenes:
            scene_number = int(scene.get("scene_number", 0))

            scene_prompts: List[ProductionPrompt] = []

            for shot in scene.get("shots", []):
                prompt = self._generate_shot_prompt(
                    shot=shot,
                    asset_planning=asset_planning,
                )

                scene_prompts.append(prompt)
                total_shots += 1

            scenes.append(
                SceneProductionPrompts(
                    scene_number=scene_number,
                    prompts=scene_prompts,
                )
            )

        return EpisodeProductionPrompts(
            episode_id=episode_id,
            title=title,
            target_duration_seconds=target_duration_seconds,
            scenes=scenes,
            total_shots=total_shots,
        )

    def _generate_shot_prompt(
        self,
        shot: Dict[str, Any],
        asset_planning: Optional[Dict[str, Any]] = None,
    ) -> ProductionPrompt:
        """
        Generate prompts for one shot.
        """

        shot_id = shot.get("shot_id", "")
        scene_number = int(shot.get("scene_number", 0))
        duration_seconds = int(shot.get("duration_seconds", 0))

        image_prompt = self._build_image_prompt(shot)

        video_prompt = self._build_video_prompt(shot)

        negative_prompt = self._build_negative_prompt(shot)

        assets = self._build_assets(
            shot=shot,
            asset_planning=asset_planning,
        )

        dialogue = shot.get("dialogue")

        return ProductionPrompt(
            shot_id=shot_id,
            scene_number=scene_number,
            duration_seconds=duration_seconds,
            image_prompt=image_prompt,
            video_prompt=video_prompt,
            negative_prompt=negative_prompt,
            assets=assets,
            dialogue=dialogue,
        )

    # ------------------------------------------------------------------
    # IMAGE PROMPT
    # ------------------------------------------------------------------

    def _build_image_prompt(
        self,
        shot: Dict[str, Any],
    ) -> str:
        """
        Build the visual keyframe prompt.
        """

        sections: List[str] = []

        sections.append(
            "Cinematic animated film frame."
        )

        purpose = shot.get("purpose")

        if purpose:
            sections.append(
                f"Shot purpose: {purpose}"
            )

        characters = shot.get("characters", [])

        if characters:
            sections.append(
                "Characters in the shot: "
                + ", ".join(characters)
                + "."
            )

        props = shot.get("props", [])

        if props:
            sections.append(
                "Props present: "
                + ", ".join(props)
                + "."
            )

        camera = shot.get("camera", {})

        camera_description = self._format_camera(camera)

        if camera_description:
            sections.append(
                f"Camera: {camera_description}"
            )

        character_actions = shot.get("character_actions", [])

        character_action_description = self._format_character_actions(
            character_actions
        )

        if character_action_description:
            sections.append(
                f"Character performance: {character_action_description}"
            )

        prop_actions = shot.get("prop_actions", [])

        prop_action_description = self._format_prop_actions(
            prop_actions
        )

        if prop_action_description:
            sections.append(
                f"Prop behavior: {prop_action_description}"
            )

        visual_constraints = shot.get("visual_constraints", [])

        if visual_constraints:
            sections.append(
                "Visual continuity and constraints: "
                + " ".join(visual_constraints)
            )

        sections.append(
            "Maintain consistent character identity, wardrobe, "
            "environment design, lighting, proportions, and cinematic style."
        )

        sections.append(
            "The frame should feel like a polished cinematic animated "
            "mystery drama, with controlled acting and restrained visual movement."
        )

        return " ".join(sections)

    # ------------------------------------------------------------------
    # VIDEO PROMPT
    # ------------------------------------------------------------------

    def _build_video_prompt(
        self,
        shot: Dict[str, Any],
    ) -> str:
        """
        Build the motion/video generation prompt.

        The prompt intentionally emphasizes controlled movement because
        AI video generation can introduce unwanted motion.
        """

        sections: List[str] = []

        camera = shot.get("camera", {})

        camera_movement = camera.get(
            "camera_movement",
            "STATIC",
        )

        framing = camera.get(
            "framing",
            "",
        )

        composition = camera.get(
            "composition",
            "",
        )

        sections.append(
            f"Generate a {shot.get('duration_seconds', 0)} second "
            "cinematic animated shot."
        )

        if framing:
            sections.append(
                f"Maintain {framing.lower()} framing."
            )

        if composition:
            sections.append(
                f"Maintain the established composition: {composition}"
            )

        sections.append(
            f"Camera movement: {camera_movement}."
        )

        character_actions = shot.get("character_actions", [])

        character_motion = self._format_video_character_actions(
            character_actions
        )

        if character_motion:
            sections.append(
                f"Character motion: {character_motion}"
            )

        prop_actions = shot.get("prop_actions", [])

        prop_motion = self._format_prop_actions(
            prop_actions
        )

        if prop_motion:
            sections.append(
                f"Prop motion: {prop_motion}"
            )

        sections.append(
            "Use subtle, controlled movement."
        )

        sections.append(
            "Preserve the character's identity and wardrobe throughout "
            "the entire shot."
        )

        sections.append(
            "Preserve the environment and lighting throughout the shot."
        )

        sections.append(
            "Do not introduce new characters or unrelated objects."
        )

        sections.append(
            "Do not create artificial transitions."
        )

        sections.append(
            "Do not add page flipping, object morphing, camera spins, "
            "or sudden zooms unless explicitly requested by the shot."
        )

        sections.append(
            "Avoid exaggerated facial expressions or body movement."
        )

        return " ".join(sections)

    # ------------------------------------------------------------------
    # NEGATIVE PROMPT
    # ------------------------------------------------------------------

    def _build_negative_prompt(
        self,
        shot: Dict[str, Any],
    ) -> str:
        """
        Build a reusable negative prompt based on the shot constraints.
        """

        negative_items = [
            "unwanted characters",
            "extra people",
            "extra props",
            "incorrect wardrobe",
            "character identity drift",
            "facial identity changes",
            "body deformation",
            "extra fingers",
            "extra limbs",
            "unwanted head turns",
            "exaggerated acting",
            "dramatic camera movement",
            "camera spin",
            "sudden zoom",
            "random camera shake",
            "object morphing",
            "environment changes",
            "lighting changes",
            "weather changes",
            "random rain",
            "artificial transitions",
            "page flipping animation",
            "unwanted text",
            "unrelated text",
            "inconsistent proportions",
            "visual glitches",
        ]

        visual_constraints = shot.get(
            "visual_constraints",
            [],
        )

        constraint_text = " ".join(
            str(constraint).lower()
            for constraint in visual_constraints
        )

        if "do not introduce rain" in constraint_text:
            negative_items.append("rain")

        if "do not introduce additional characters" in constraint_text:
            negative_items.append("additional characters")

        if "do not introduce new characters" in constraint_text:
            negative_items.append("new characters")

        if "avoid unnecessary head movement" in constraint_text:
            negative_items.append("unnecessary head movement")

        if "avoid unnecessary character movement" in constraint_text:
            negative_items.append("unnecessary character movement")

        if "do not zoom excessively close" in constraint_text:
            negative_items.append("excessive zoom")

        if "do not animate page flipping" in constraint_text:
            negative_items.append("page flipping")

        return ", ".join(self._deduplicate(negative_items))

    # ------------------------------------------------------------------
    # ASSET HANDLING
    # ------------------------------------------------------------------

    def _build_assets(
        self,
        shot: Dict[str, Any],
        asset_planning: Optional[Dict[str, Any]] = None,
    ) -> List[PromptAssetReference]:
        """
        Convert execution asset references into prompt asset references.

        The current production execution output already contains the
        required assets, so that data is preferred.
        """

        result: List[PromptAssetReference] = []

        shot_assets = shot.get("assets", [])

        if shot_assets:
            for asset in shot_assets:
                result.append(
                    PromptAssetReference(
                        asset_id=asset.get("asset_id", ""),
                        entity_id=asset.get("entity_id", ""),
                        asset_type=asset.get("asset_type", ""),
                        name=asset.get("name", ""),
                        purpose=asset.get("purpose"),
                        reference_path=asset.get("reference_path"),
                        required=asset.get("required", True),
                        master_reference_required=asset.get(
                            "master_reference_required",
                            False,
                        ),
                    )
                )

            return result

        # Fallback:
        # If execution does not contain assets, try to retrieve them
        # from asset planning.
        if asset_planning:
            planned_assets = self._find_planned_assets(
                shot_id=shot.get("shot_id", ""),
                asset_planning=asset_planning,
            )

            for asset in planned_assets:
                result.append(
                    PromptAssetReference(
                        asset_id=asset.get("asset_id", ""),
                        entity_id=asset.get("entity_id", ""),
                        asset_type=asset.get("asset_type", ""),
                        name=asset.get("name", ""),
                        purpose=asset.get("purpose"),
                        reference_path=asset.get("reference_path"),
                        required=asset.get("required", True),
                        master_reference_required=asset.get(
                            "master_reference_required",
                            False,
                        ),
                    )
                )

        return result

    def _find_planned_assets(
        self,
        shot_id: str,
        asset_planning: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """
        Find assets belonging to a specific shot from asset planning.
        """

        scenes = asset_planning.get("scenes", [])

        for scene in scenes:
            shots = scene.get("shots", [])

            for shot in shots:
                if shot.get("shot_id") == shot_id:
                    return shot.get("assets", [])

        return []

    # ------------------------------------------------------------------
    # CAMERA FORMATTING
    # ------------------------------------------------------------------

    def _format_camera(
        self,
        camera: Dict[str, Any],
    ) -> str:
        """
        Convert camera configuration into natural language.
        """

        if not camera:
            return ""

        parts: List[str] = []

        shot_type = camera.get("shot_type")

        if shot_type:
            parts.append(
                f"shot type {shot_type}"
            )

        camera_movement = camera.get("camera_movement")

        if camera_movement:
            parts.append(
                f"camera movement {camera_movement}"
            )

        framing = camera.get("framing")

        if framing:
            parts.append(
                f"framing {framing}"
            )

        composition = camera.get("composition")

        if composition:
            parts.append(
                f"composition: {composition}"
            )

        return ", ".join(parts)

    # ------------------------------------------------------------------
    # CHARACTER ACTION FORMATTING
    # ------------------------------------------------------------------

    def _format_character_actions(
        self,
        actions: List[Dict[str, Any]],
    ) -> str:
        """
        Convert structured character actions into readable text.
        """

        if not actions:
            return ""

        descriptions: List[str] = []

        for action in actions:
            entity_id = action.get(
                "entity_id",
                "character",
            )

            action_name = action.get(
                "action",
                "",
            )

            gesture = action.get(
                "gesture",
                "",
            )

            facial_movement = action.get(
                "facial_movement",
                "",
            )

            parts = [
                entity_id,
                action_name,
            ]

            if gesture:
                parts.append(
                    f"gesture {gesture}"
                )

            if facial_movement:
                parts.append(
                    f"facial expression {facial_movement}"
                )

            descriptions.append(
                " ".join(
                    part
                    for part in parts
                    if part
                )
            )

        return "; ".join(descriptions)

    def _format_video_character_actions(
        self,
        actions: List[Dict[str, Any]],
    ) -> str:
        """
        Convert character actions into motion-specific instructions.
        """

        if not actions:
            return ""

        descriptions: List[str] = []

        for action in actions:
            entity_id = action.get(
                "entity_id",
                "character",
            )

            action_name = action.get(
                "action",
                "",
            )

            gesture = action.get(
                "gesture",
                "",
            )

            facial_movement = action.get(
                "facial_movement",
                "",
            )

            description = (
                f"{entity_id} performs {action_name}"
            )

            if gesture:
                description += (
                    f" with {gesture.lower()}"
                )

            if facial_movement:
                description += (
                    f"; facial movement remains {facial_movement.lower()}"
                )

            descriptions.append(
                description
            )

        return "; ".join(descriptions) + "."

    # ------------------------------------------------------------------
    # PROP FORMATTING
    # ------------------------------------------------------------------

    def _format_prop_actions(
        self,
        actions: List[Dict[str, Any]],
    ) -> str:
        """
        Convert structured prop actions into readable text.
        """

        if not actions:
            return ""

        descriptions: List[str] = []

        for action in actions:
            entity_id = action.get(
                "entity_id",
                "prop",
            )

            action_name = action.get(
                "action",
                "",
            )

            descriptions.append(
                f"{entity_id} {action_name}"
            )

        return "; ".join(descriptions)

    # ------------------------------------------------------------------
    # HELPERS
    # ------------------------------------------------------------------

    def _deduplicate(
        self,
        items: List[str],
    ) -> List[str]:
        """
        Remove duplicate strings while preserving order.
        """

        seen = set()
        result = []

        for item in items:
            normalized = item.strip().lower()

            if normalized in seen:
                continue

            seen.add(normalized)
            result.append(item)

        return result